name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.12'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm run build:all

      - name: Create Chrome Extension Zip
        run: zip -r extension/chrome/dist/chrome-extension.zip extension/chrome/dist

      - name: Create Edge Extension Zip
        run: zip -r extension/edge/dist/edge-extension.zip extension/edge/dist

      - name: Create Firefox Extension Zip
        run: zip -r extension/firefox/dist/firefox-extension.zip extension/firefox/dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Chrome Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: extension/chrome/dist/chrome-extension.zip
          asset_name: chrome-extension.zip
          asset_content_type: application/zip

      - name: Upload Edge Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: extension/edge/dist/edge-extension.zip
          asset_name: edge-extension.zip
          asset_content_type: application/zip

      - name: Upload Firefox Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: extension/firefox/dist/firefox-extension.zip
          asset_name: firefox-extension.zip
          asset_content_type: application/zip
